### Findings

- Unbranded items are made by 208 various manufacturers, 256 brands have a single manufacturer each, 16 brands have two manufacturers each, while Brands 93 and 120 have four manufacturers each.


- Notable Labels for `category1` and `category3` are 1 and 8 as these appear to either have one of the highest average customer ratings or highest average retail prices.



### Tasks

- Performed bivariate analysis of the `items` dataset, not quite in depth.


- Investigated the relationship between `brand` and `manufacturer`, between `brand` and `customerRating`+`recommendedRetailPrice`, and between the three `category1`,`2`,`3` and ratings + retail price.


**Ismail Dawoodjee | 10:26 PM 02-June-2020**

# Data Exploration Part 3

Bivariate analysis of variables in the `items` dataset will be carried out in this notebook.

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style = 'whitegrid')

In [2]:
items = pd.read_pickle('items.pkl')

In [3]:
items

itemID  brand  manufacturer  customerRating  modifiedRating  category1  \
0           1      0             1            4.38             4.5          1   
1           2      0             2            3.00             3.0          1   
2           3      0             3            5.00             5.0          1   
3           4      0             2            4.44             4.5          1   
4           5      0             2            2.33             2.5          1   
...       ...    ...           ...             ...             ...        ...   
10458   10459    180           253            0.00             0.0          8   
10459   10460      0           253            0.00             0.0          8   
10460   10461      0           253            0.00             0.0          8   
10461   10462    180           253            0.00             0.0          8   
10462   10463      0           253            0.00             0.0          8   

       category2  category3  recommendedRetailPrice  
0              1          1                    8.84  
1              2          1                   16.92  
2              3          1                   15.89  
3              2          1                   40.17  
4              1          1                   17.04  
...          ...        ...                     ...  
10458         44          8                   56.57  
10459         44          8                  163.81  
10460         44          8                  128.01  
10461         44          8                  166.97  
10462         44          8                  154.82  

[10463 rows x 9 columns]

**1. How many manufacturers produced items for each brand?** Looking at number of unqiue manufacturers for each brand.

In [4]:
brand_uniq = items.groupby(by = 'brand').nunique()

In [5]:
brand_uniq.head(6)

itemID  brand  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                           
0        5232      1           208              75              10          8   
1          33      1             2               3               3          1   
2          89      1             1              14               7          3   
3           8      1             1               2               2          1   
4          71      1             1               8               7          1   
5          11      1             1               5               4          1   

       category2  category3  recommendedRetailPrice  
brand                                                
0             48          8                    2945  
1              6          1                      33  
2              6          2                      89  
3              1          1                       8  
4              1          1                      49  
5              1          1                      11

In [6]:
brand_uniq[brand_uniq['manufacturer'] > 2]

itemID  brand  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                           
0        5232      1           208              75              10          8   
93        161      1             4              14               8          1   
120        24      1             4               8               7          1   

       category2  category3  recommendedRetailPrice  
brand                                                
0             48          8                    2945  
93             1          1                     143  
120            2          1                      24

In [34]:
(brand_uniq['manufacturer'] == 2).sum(), (brand_uniq['manufacturer'] == 1).sum()

(16, 256)

- Items with no brand are produced by 208 unique manufacturers, Brands 93 and 120 have four manufacturers each, 16 brands have two manufacturers each, and the remaining 256 brands have a single manufacturer. 
- Similar deductions can be made for `category1`,`2` and `3`.

**2. What are the brands with the highest and lowest customer ratings and retail prices?** Looking at mean `customerRating` and `recommendedRetailPrice` for each brand.

In [8]:
brand_mean = items.groupby(by = 'brand').mean()

In [9]:
brand_mean.head(6)

itemID  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                         
0      4064.096904     89.389908        1.362756        1.362385   3.465405   
1       771.333333     13.121212        0.727273        0.727273   1.000000   
2      6951.056180      3.000000        2.676404        2.679775   6.820225   
3      1809.500000     37.000000        1.250000        1.250000   2.000000   
4      2607.422535     38.000000        1.687746        1.690141   2.000000   
5      2104.454545     40.000000        1.840909        1.818182   2.000000   

       category2  category3  recommendedRetailPrice  
brand                                                
0      16.888188   3.113723               87.040591  
1       5.060606   1.000000              941.945758  
2      23.921348   5.887640               27.205843  
3       8.000000   2.000000               38.127500  
4       8.000000   2.000000               31.230141  
5       9.000000   2.000000               19.933636

In [49]:
brand_mean.sort_values(by = 'recommendedRetailPrice')

itemID  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                      
170     8665.00         186.0            0.00            0.00        4.0   
169     8663.00         186.0            0.00            0.00        4.0   
172     8676.00         202.0            5.00            5.00        4.0   
83      4256.00         101.0            5.00            5.00        3.0   
100     5953.00         162.0            0.00            0.00        5.0   
...         ...           ...             ...             ...        ...   
200     9180.25         128.0            2.00            2.00        8.0   
242     9780.50         251.0            1.25            1.25        8.0   
258    10077.50         244.0            0.00            0.00        8.0   
241    10116.50         251.0            2.50            2.50        8.0   
238     9676.00         128.0            0.00            0.00        8.0   

       category2  category3  recommendedRetailPrice  
brand                                                
170         39.0        7.0                3.580000  
169         42.0        7.0                4.183333  
172         39.0        7.0                4.720000  
83          12.0        3.0                6.100000  
100         32.0        4.0                6.425000  
...          ...        ...                     ...  
200         44.0        8.0             1382.960000  
242         44.0        8.0             1828.800000  
258         44.0        8.0             1902.133333  
241         44.0        8.0             2072.750000  
238         44.0        8.0             2813.700000  

[275 rows x 8 columns]

- The 5 most expensive and least expensive brands can be seen above.
- To look at the average ratings for each brand, unrated items will have to be excluded first.

In [3]:
nonzero_ratings = items[items['customerRating'] != 0]

In [12]:
nonzero_ratings_mean = nonzero_ratings.groupby(by = 'brand').mean()

In [14]:
nonzero_ratings_mean.head(6)

itemID  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                         
0      3860.624227     81.874536        4.406638        4.405439   3.399876   
1      1044.200000     13.000000        4.800000        4.800000   1.000000   
2      7034.326923      3.000000        4.580769        4.586538   6.923077   
3      1807.500000     37.000000        5.000000        5.000000   2.000000   
4      2512.233333     38.000000        3.994333        4.000000   2.000000   
5      2057.400000     40.000000        4.050000        4.000000   2.000000   

       category2  category3  recommendedRetailPrice  
brand                                                
0      16.524722   3.168109               45.683758  
1       5.800000   1.000000             1668.554000  
2      24.461538   6.000000               27.145192  
3       8.000000   2.000000               40.495000  
4       8.000000   2.000000               31.097000  
5       9.000000   2.000000               23.614000

In [21]:
# sort by rating, then price
nonzero_ratings_mean.sort_values(by = ['customerRating','recommendedRetailPrice'])

itemID  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                          
29      2532.000000          58.0           1.000            1.00        2.0   
96      5033.000000         100.0           1.500            1.50        5.0   
236     9626.000000         240.0           2.000            2.00        8.0   
106     7078.000000         152.0           2.000            2.00        7.0   
104     6777.800000         172.0           2.567            2.55        7.0   
...             ...           ...             ...             ...        ...   
262    10237.333333         242.0           5.000            5.00        8.0   
201    10313.000000         244.0           5.000            5.00        8.0   
230     9524.000000         246.0           5.000            5.00        8.0   
242     9782.000000         251.0           5.000            5.00        8.0   
241     9778.000000         251.0           5.000            5.00        8.0   

       category2  category3  recommendedRetailPrice  
brand                                                
29          10.0        2.0                  20.730  
96          30.0        4.0                  12.180  
236         44.0        8.0                  86.840  
106         23.0        6.0                 126.440  
104         23.0        6.0                  13.474  
...          ...        ...                     ...  
262         43.0        8.0                 304.610  
201         44.0        8.0                 462.000  
230         44.0        8.0                 770.000  
242         44.0        8.0                2326.500  
241         44.0        8.0                3108.000  

[177 rows x 8 columns]

In [22]:
# sort by price, then rating
nonzero_ratings_mean.sort_values(by = ['recommendedRetailPrice', 'customerRating'])

itemID  manufacturer  customerRating  modifiedRating  category1  \
brand                                                                         
172    8676.000000         202.0        5.000000         5.00000        4.0   
91     4990.000000          66.0        3.000000         3.00000        5.0   
83     4256.000000         101.0        5.000000         5.00000        3.0   
53     2777.500000          67.0        4.500000         4.50000        2.0   
167    8613.800000         213.0        3.734000         3.70000        4.0   
...            ...           ...             ...             ...        ...   
200    8972.625000         128.0        4.000000         4.00000        8.0   
178    9319.591837         225.0        4.751224         4.77551        8.0   
1      1044.200000          13.0        4.800000         4.80000        1.0   
242    9782.000000         251.0        5.000000         5.00000        8.0   
241    9778.000000         251.0        5.000000         5.00000        8.0   

       category2  category3  recommendedRetailPrice  
brand                                                
172    39.000000        7.0                4.720000  
91     28.000000        4.0                5.565000  
83     12.000000        3.0                6.100000  
53     11.000000        2.0                7.130000  
167    34.000000        7.0                7.250000  
...          ...        ...                     ...  
200    44.000000        8.0             1275.755000  
178    43.897959        8.0             1352.638367  
1       5.800000        1.0             1668.554000  
242    44.000000        8.0             2326.500000  
241    44.000000        8.0             3108.000000  

[177 rows x 8 columns]

**3. Which `categories` have the highest and lowest customer ratings and retail prices?** Looking at mean `customerRating` and `recommendedRetailPrice` for each `category1`,`2`, and `3`.

- **3.1. Looking at `category1`**, first for all items and then for items with non-zero ratings.

In [5]:
items.groupby(by = 'category1').mean().sort_values(by = 'recommendedRetailPrice')

itemID       brand  manufacturer  customerRating  \
category1                                                          
4          8188.528380   88.610939    173.394221        2.320041   
5          5779.340083   36.303157    139.080405        1.225652   
7          6701.163247   27.399643    135.531668        1.336459   
2          3019.425468   27.695486     66.053663        1.206478   
6          4502.756646   11.576687    100.844581        1.379346   
1           986.799781    0.119583     15.276467        1.552792   
3          6246.740000    6.940000    153.203333        0.560233   
8          9589.272780  194.082468    218.570358        1.402307   

           modifiedRating  category2  category3  recommendedRetailPrice  
category1                                                                
4                2.319917  37.389061   6.962848               18.271259  
5                1.224836  29.675998   3.994044               19.905533  
7                1.335415  23.796610   5.694023               26.045210  
2                1.205920   9.416951   2.007666               39.589915  
6                1.379346  19.190184   3.010225               56.242679  
1                1.554032   3.346681   1.000000              162.989813  
3                0.560000  28.963333   4.236667              350.684067  
8                1.403114  44.102076   8.000000              365.904354

In [7]:
nonzero_ratings.groupby(by = 'category1').mean().sort_values(by = 'customerRating')

itemID       brand  manufacturer  customerRating  \
category1                                                          
3          5341.720930   12.069767    123.348837        3.908605   
6          4422.126506   14.524096     94.644578        4.063253   
4          8123.228407   82.000000    169.299424        4.315010   
5          5504.484211   39.275789    118.404211        4.332358   
2          2923.813375   29.391913     62.763608        4.405614   
7          6698.170588   23.611765    124.267647        4.406382   
8          9374.754190  185.681564    218.089385        4.528119   
1           856.048309    0.008052     16.351047        4.558357   

           modifiedRating  category2  category3  recommendedRetailPrice  
category1                                                                
3                3.906977  26.837209   3.813953              165.761395  
6                4.063253  19.307229   3.018072               36.000000  
4                4.314779  37.320537   6.982726               17.414261  
5                4.329474  27.901053   3.995789               20.055137  
2                4.403577   9.197512   2.000000               34.569642  
7                4.402941  23.591176   5.905882               24.875559  
8                4.530726  44.098696   8.000000              366.880596  
1                4.561997   3.333333   1.000000               83.012673

- In `category1`, Labels 1, 8 and 7 (in order) are seen to have the highest customer ratings while the Labels 8, 3, 1 have the highest average retail price.

- **3.2. Looking at `category2`**

In [9]:
# 5 lowest retail prices by category2
items.groupby(by = 'category2').mean().sort_values(by = 'recommendedRetailPrice').head()

itemID       brand  manufacturer  customerRating  \
category2                                                           
51          8867.000000    0.000000     23.000000        0.000000   
52         10021.000000  252.500000    229.000000        0.000000   
41          8196.372881  103.355932    200.474576        1.990339   
21          5133.732484   57.675159     84.668790        3.300510   
32          5949.000000   32.582488    161.707834        0.848959   

           modifiedRating  category1  category3  recommendedRetailPrice  
category2                                                                
51               0.000000        8.0   8.000000                6.400000  
52               0.000000        8.0   8.000000                9.630000  
41               1.983051        4.0   7.000000               11.177966  
21               3.308917        5.0   3.993631               13.337834  
32               0.847465        5.0   4.000000               13.892654

In [10]:
# 5 highest retail prices by category2
items.groupby(by = 'category2').mean().sort_values(by = 'recommendedRetailPrice').tail()

itemID       brand  manufacturer  customerRating  \
category2                                                          
49         9596.250000  125.500000    196.500000        1.250000   
16         4391.000000   33.000000     93.814815        1.532222   
44         9603.256677  202.078635    221.632789        1.433234   
34         7656.342541    0.011050    193.265193        0.220994   
7           662.958333    0.375000     12.583333        0.666667   

           modifiedRating  category1  category3  recommendedRetailPrice  
category2                                                                
49               1.250000        8.0   8.000000              249.470000  
16               1.537037        6.0   2.962963              359.489630  
44               1.434718        8.0   8.000000              423.652300  
34               0.220994        3.0   5.005525              536.006575  
7                0.666667        1.0   1.000000              592.601250

In [12]:
# 5 lowest customer ratings by category2
nonzero_ratings.groupby(by = 'category2').mean().sort_values(by = 'customerRating').head()

itemID       brand  manufacturer  customerRating  \
category2                                                          
46         8783.000000  180.000000    128.000000        2.000000   
34         7580.230769    0.153846    179.307692        3.076923   
18         4388.692308    6.192308     86.730769        3.275769   
29         4460.642857   24.142857    101.000000        3.623571   
27         4454.333333   80.000000     93.000000        3.666667   

           modifiedRating  category1  category3  recommendedRetailPrice  
category2                                                                
46               2.000000        8.0   8.000000               42.290000  
34               3.076923        3.0   5.076923              427.826923  
18               3.269231        6.0   3.000000               14.223462  
29               3.642857        3.0   3.000000               80.901429  
27               3.666667        6.0   3.000000               75.000000

In [14]:
# 5 highest customer ratings by category2
nonzero_ratings.groupby(by = 'category2').mean().sort_values(by = 'customerRating').tail()

itemID      brand  manufacturer  customerRating  \
category2                                                         
12         3581.100000  17.900000          85.0           4.867   
36         7330.000000   2.000000           3.0           5.000   
26         5779.333333   0.333333         102.0           5.000   
49         9599.500000  94.000000         181.5           5.000   
35         6782.000000   0.000000         100.0           5.000   

           modifiedRating  category1  category3  recommendedRetailPrice  
category2                                                                
12                   4.85        3.0        2.6               35.725000  
36                   5.00        7.0        6.0               36.780000  
26                   5.00        7.0        5.5              233.578333  
49                   5.00        8.0        8.0              252.170000  
35                   5.00        7.0        6.0               63.130000

- **3.3. Looking at `category3`**, first for all items and then for items with non-zero ratings.

In [15]:
items.groupby(by = 'category3').mean().sort_values(by = 'recommendedRetailPrice')

itemID       brand  manufacturer  customerRating  \
category3                                                          
7          8232.000000   89.712644    174.167189        2.324754   
4          5785.335119   36.387500    139.149405        1.229190   
6          6911.408644   22.998035    136.292731        1.452073   
2          3005.500000   27.646667     65.884167        1.194921   
3          4548.339009   20.981424    105.964396        1.201780   
1           986.799781    0.119583     15.276467        1.552792   
8          9589.043228  193.970605    218.580980        1.401499   
5          7460.107843    0.000000    185.426471        0.330098   

           modifiedRating  category1  category2  recommendedRetailPrice  
category3                                                                
7                2.324451   4.000000  37.682341               18.420721  
4                1.228274   5.008333  29.670833               20.006518  
6                1.451375   6.953831  23.599214               24.778389  
2                1.194375   2.028750   9.483750               40.189067  
3                1.202012   5.950464  20.784830               54.134675  
1                1.554032   1.000000   3.346681              162.989813  
8                1.402305   7.996542  44.082997              365.782553  
5                0.328431   3.000000  33.254902              480.120637

In [16]:
nonzero_ratings.groupby(by = 'category3').mean().sort_values(by = 'customerRating')

itemID       brand  manufacturer  customerRating  \
category3                                                          
5          6971.157895    0.000000    170.315789        3.544211   
3          4430.692708   15.604167     96.020833        4.043490   
7          8144.496124   82.794574    169.451550        4.311609   
4          5503.316562   39.111111    118.272537        4.329224   
2          2919.733846   29.223077     62.727692        4.412015   
6          6764.595808   23.550898    125.065868        4.425778   
8          9374.754190  185.681564    218.089385        4.528119   
1           856.048309    0.008052     16.351047        4.558357   

           modifiedRating  category1  category2  recommendedRetailPrice  
category3                                                                
5                3.526316   3.000000  31.894737              297.518421  
3                4.044271   5.765625  20.208333               38.941927  
7                4.311047   4.000000  37.546512               17.521919  
4                4.325996   5.016771  27.861635               20.115157  
2                4.410000   2.012308   9.230769               34.661185  
6                4.423653   6.949102  23.476048               24.230599  
8                4.530726   8.000000  44.098696              366.880596  
1                4.561997   1.000000   3.333333               83.012673

- For `category3`, Labels 1, 8 and 6 are seen to have the highest ratings and labels 5, 8 and 1 have the highest retail prices.